#pragma once

#include <vector>
#include "SGB_Timer.h"
#include "SGB_types.h"

/*! \brief Internal class. Handles timing managemente for a `SGB_Display`. */
class SGB_DisplayTimingManager
{
public:
	SGB_DisplayTimingManager();
	~SGB_DisplayTimingManager();

	/*! \brief Prepare the timing manager
	*
	* \param info The `SGB_DisplayInitInfo` generated by the parent `SGB_Display`.
	*/
	void Setup(SGB_DisplayInitInfo info);

	/*! \brief Starts a `SGB_Timer` to keep track of the total running time */
	Uint32 StartGlobalTimer();

	/*! \brief Gets the most recent calculated average framerate. */
	Uint32 CalculateAverageFPS();

	/*! \brief Gets the total ticks since the global timer started.*/
	Uint32 GetGlobalTicks();

	/*! \brief Gets the total ticks since the last loop cycle.*/
	Uint32 GetDeltaTicks();

	/*! \brief Resets the delta timer used to calculate time
	* since the last loop cycle
	*/
	void ResetDeltaTimer();

	/*! \brief Updates counter for FPS calculation and delays the next cycle if
	* necessary.
	*/
	void FinishCycle();

private:
	//The frames per second timer
	SGB_Timer fpsTimer;

	//The frames per second cap timer
	SGB_Timer capTimer;

	//Timer to measure how much time has passed since the last =BeginUpdate= happened
	SGB_Timer stepTimer;

	//Counter to accumulate how many frames have passed since the last FPS sampling
	int countedFrames;

	//Stores when the last FPS sampling happened
	Uint32 lastCountReset;

	//Stores how much time is expected to pass between frame rendering and calculation
	Uint32 frameInterval;

	//Store the last (_initInfo.FrameRateSamplesPerSecond) framecounts between FPS samplings
	std::vector<Uint32> _fpsQueue;

	SGB_DisplayInitInfo _initInfo;

	Uint32 _currentAverageFPS;
};

